// Copyright 2019-2022 Collabora Ltd.
// SPDX-License-Identifier: MIT

#ifndef SYSROOT_TARBALL
#   error SYSROOT_TARBALL must be defined
#endif

FROM scratch
ADD SYSROOT_TARBALL /

#ifdef NOPASSWD
RUN mkdir -p /etc/sudoers.d && echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/flatdeb && chmod 0440 /etc/sudoers.d/flatdeb
#endif

#ifdef OS_RELEASE_LABELS
OS_RELEASE_LABELS
#endif

#ifdef TOOLBX
LABEL com.github.containers.toolbox="true"
LABEL com.github.debarshiray.toolbox="true"
#endif

CMD ["/bin/bash"]

// vim:set sw=4 sts=4 et:
