#!/bin/bash

# Copyright © 2016-2017 Simon McVittie
# Copyright © 2017-2018 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e
set -u
set -o pipefail

me="$(basename "$0")"
NULL=

if [ "$#" != 1 ] || [ "$1" = '--help' ] || [ "x$(id -u)" != x0 ] ||
        ! [ -d "$1" ]; then
    echo "$me: Usage:" >&2
    echo "    $me SYSROOT" >&2
    echo "" >&2
    echo "Run this script as root." >&2
    exit 2
fi

sysroot="$1"
cd "$sysroot"

in_chroot () {
    chroot "$sysroot" "$@"
}

rm -fr \
etc/.pwd.lock \
etc/group- \
etc/machine-id \
etc/passwd- \
etc/shadow- \
etc/subgid- \
etc/subuid- \
home \
media \
mnt \
opt \
root \
run \
srv \
tmp \
var/cache \
var/lib/aptitude/pkgstates.old \
var/lib/dbus/machine-id \
var/lib/dpkg/available-old \
var/lib/dpkg/diversions-old \
var/lib/dpkg/status-old \
var/lib/urandom \
var/lock \
var/tmp \
${NULL}

# For portability between systems, especially if we're exporting a
# sysroot tarball for schroot (which assumes it can use host uids and
# gids for the chroot), we don't want to include /var/lib/apt/lists/*/
# in the tarball if they are owned by _apt. We can just delete them -
# apt will recreate them as needed.
for dir in \
    var/lib/apt/lists/auxfiles \
    var/lib/apt/lists/partial \
; do
    if [ -e "$dir" ] \
    && [ "x$(command stat -c '%u:%g' "$dir")" != "x0:0" ]; then
        rm -fr "$dir"
    fi
done

install -d root
install -d run
install -d run/lock
install -d -m1777 tmp
install -d var/cache
install -d -m1777 var/tmp
ln -s /dev/shm run/shm
ln -s /run/lock var/lock
