#!/usr/bin/python3

# flatdeb — build Flatpak runtimes from Debian packages
#
# Copyright © 2016-2017 Simon McVittie
# Copyright © 2017-2018 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
Fetch source code for packages installed in the given sysroot.
"""

import argparse
import logging
import os
import subprocess
import sys

try:
    import typing
except ImportError:
    pass
else:
    typing  # silence "unused" warnings


logger = logging.getLogger('flatdeb.collect-dbgsym')


class InstalledPackage:
    def __init__(self, fields):
        # type: (typing.Sequence[str]) -> None
        self.binary = fields[0]
        self.binary_version = fields[1]

    def __str__(self):
        # type: () -> str
        return '{}_{}'.format(self.binary, self.binary_version)

    def __hash__(self):
        # type: () -> int
        return hash(self.binary) ^ hash(self.binary_version)

    def __eq__(self, other):
        # type: (typing.Any) -> bool
        if isinstance(other, InstalledPackage):
            return (
                self.binary,
                self.binary_version,
            ) == (
                other.binary,
                other.binary_version,
            )
        else:
            return NotImplemented

    @property
    def dbgsym_package(self):
        # type: () -> str

        if ':' in self.binary:
            return self.binary.replace(':', '-dbgsym:')
        else:
            return self.binary + '-dbgsym'


def read_manifest(path):
    # type: (str) -> typing.List[InstalledPackage]

    ret = []

    with open(path, encoding='utf-8') as reader:
        for line in reader:
            line = line.rstrip('\n')

            if not line:
                continue

            if line.startswith('#'):
                continue

            assert '\t' in line, repr(line)
            ret.append(InstalledPackage(line.rstrip('\n').split('\t')))

    return ret


def main():
    # type: (...) -> None
    parser = argparse.ArgumentParser(
        description='Install corresponding -dbgsym packages if available',
    )
    parser.add_argument('sysroot')

    args = parser.parse_args()

    in_chroot = [
        'systemd-nspawn',
        '--directory={}'.format(args.sysroot),
        '--as-pid2',
        '--tmpfs=/run/lock',
    ]
    in_chroot_quick = [
        'chroot', args.sysroot,
    ]

    in_chroot.append('env')

    for var in ('ftp_proxy', 'http_proxy', 'https_proxy', 'no_proxy'):
        if var in os.environ:
            in_chroot.append('{}={}'.format(var, os.environ[var]))

    platform_manifest = os.path.join(
        args.sysroot, 'usr', 'manifest.dpkg.platform')

    if os.path.exists(platform_manifest):
        platform_packages = read_manifest(platform_manifest)
    else:
        platform_packages = []

    to_get = []     # type: typing.List[str]

    for p in platform_packages:
        logger.info('Package in Platform: %s', p)
        to_get.append('{}={}'.format(p.dbgsym_package, p.binary_version))

    subprocess.run(in_chroot + [
        'sh', '-euc', '''
        for x in "$@"; do
            apt-get -y -q -q -m install "$x" || true
        done
        ''',
        'sh',   # $0
    ] + to_get)

    parent = os.path.join(
        args.sysroot, 'usr', 'lib', 'debug',
    )
    os.makedirs(parent, exist_ok=True)

    with open(
        os.path.join(parent, 'dbgsym-packages-installed.txt'),
        'w',
    ) as writer, open(
        os.path.join(parent, 'dbgsym-packages-not-installed.txt'),
        'w',
    ) as missing_writer:
        for p in platform_packages:
            if subprocess.run(
                in_chroot_quick + [
                    'dpkg-query', '-W', p.dbgsym_package,
                ],
                stdout=writer,
                stderr=subprocess.DEVNULL,
            ).returncode == 0:
                logger.info(
                    'Installed -dbgsym package: %s_%s',
                    p.dbgsym_package,
                    p.binary_version,
                )
            else:
                result = subprocess.run(
                    in_chroot_quick + [
                        'apt-cache', '-q', 'showpkg', p.dbgsym_package,
                    ],
                    stdout=subprocess.PIPE,
                )

                if result.returncode == 0 and result.stdout:
                    logger.warning(
                        'Unable to install -dbgsym package: %s_%s',
                        p.dbgsym_package,
                        p.binary_version,
                    )
                    logger.warning(
                        'Versions available:\n%s',
                        result.stdout.decode('utf-8', errors='replace'),
                    )
                    missing_writer.write('{}\t{}\n'.format(
                        p.dbgsym_package,
                        p.binary_version,
                    ))
                else:
                    logger.info(
                        'Skipped nonexistent -dbgsym package: %s',
                        p.dbgsym_package,
                    )


if __name__ == '__main__':
    if sys.stderr.isatty():
        try:
            import colorlog
        except ImportError:
            pass
        else:
            formatter = colorlog.ColoredFormatter(
                '%(log_color)s%(levelname)s:%(name)s:%(reset)s %(message)s')
            handler = logging.StreamHandler()
            handler.setFormatter(formatter)
            logging.getLogger().addHandler(handler)
    else:
        logging.basicConfig()

    logging.getLogger().setLevel(logging.DEBUG)

    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit(130)
    except subprocess.CalledProcessError as e:
        logger.error('%s', e)
        raise SystemExit(1)
