#!/usr/bin/python3

# flatdeb — build Flatpak runtimes from Debian packages
#
# Copyright © 2016-2017 Simon McVittie
# Copyright © 2017-2018 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""
Fetch source code for packages installed in the given sysroot.
"""

import argparse
import logging
import os
import subprocess
import sys

from debian.debian_support import Version

try:
    import typing
except ImportError:
    pass
else:
    typing  # silence "unused" warnings


logger = logging.getLogger('flatdeb.collect-source-code')


class SourceRequired:
    def __init__(self, source, source_version):
        # type: (str, Version) -> None
        self.source = source
        self.source_version = source_version

    def __str__(self):
        # type: () -> str
        return 'src:{}_{}'.format(self.source, self.source_version)

    def __hash__(self):
        # type: () -> int
        return hash(self.source) ^ hash(self.source_version)

    def __eq__(self, other):
        # type: (typing.Any) -> bool
        if isinstance(other, SourceRequired):
            return (
                self.source,
                self.source_version,
            ) == (
                other.source,
                other.source_version,
            )
        else:
            return NotImplemented

    def __lt__(self, other):
        # type: (typing.Any) -> bool
        if isinstance(other, SourceRequired):
            return (
                self.source,
                Version(self.source_version),
            ) < (
                other.source,
                Version(other.source_version),
            )
        else:
            return NotImplemented

    @property
    def get_source(self):
        # type: () -> str
        return '{}={}'.format(self.source, self.source_version)


def read_required(path):
    # type: (str) -> typing.Set[SourceRequired]

    ret = set()

    with open(path, encoding='utf-8') as reader:
        for line in reader:
            line = line.rstrip('\n')

            if line.startswith('#'):
                continue

            source, version = line.split('\t')
            ret.add(SourceRequired(source, version))

    return ret


def main():
    # type: (...) -> None
    parser = argparse.ArgumentParser(
        description='Collect source code',
    )
    parser.add_argument('--output', '-o', default='')
    parser.add_argument('--sysroot', default='/')
    parser.add_argument('required', nargs='+')

    args = parser.parse_args()

    in_chroot = [
        'systemd-nspawn',
        '--directory={}'.format(args.sysroot),
        '--as-pid2',
        '--tmpfs=/run/lock',
        '--register=no',
    ]

    if args.output:
        in_chroot.append(
            '--bind={}:/src/files'.format(os.path.abspath(args.output))
        )

    in_chroot.append('env')

    for var in ('ftp_proxy', 'http_proxy', 'https_proxy', 'no_proxy'):
        if var in os.environ:
            in_chroot.append('{}={}'.format(var, os.environ[var]))

    sources_required = set()

    for path in args.required:
        sources_required |= read_required(path)

    get_source = []             # type: typing.List[str]
    included = set()            # type: typing.Set[SourceRequired]
    missing_sources = set()     # type: typing.Set[SourceRequired]

    for s in sources_required:
        get_source.append(s.get_source)

    options = ['-q', '-q', '-y', '--download-only']
    options.append('-oAPT::Get::Only-Source=true')
    options.append('-oAcquire::Retries=3')

    try:
        subprocess.check_call(in_chroot + [
            'sh', '-euc',
            'dir="$1"; shift; mkdir -p "$dir"; cd "$dir"; "$@"',
            'sh',                       # argv[0]
            '/src/files',               # working directory
            'apt-get'
        ] + options + [
            'source',
        ] + get_source)
    except subprocess.CalledProcessError:
        logger.warning(
            'Unable to download some sources as a batch, trying '
            'to download sources individually')

        for s in sources_required:
            try:
                subprocess.check_call(in_chroot + [
                    'sh', '-euc',
                    'dir="$1"; shift; mkdir -p "$dir"; cd "$dir"; "$@"',
                    'sh',                       # argv[0]
                    '/src/files',               # working directory
                    'apt-get',
                ] + options + [
                    'source',
                    s.get_source,
                ])
            except subprocess.CalledProcessError:
                # Non-fatal for now
                logger.warning(
                    'Unable to get source code for %s', s.source)
                missing_sources.add(s)
                subprocess.call(in_chroot + [
                    'apt-cache', 'showsrc', s.source,
                ])
            else:
                included.add(s)
    else:
        included = set(sources_required)

    parent = args.output or os.path.join(args.sysroot, 'src', 'files')

    subprocess.check_call(in_chroot + [
        'sh', '-euc',
        'mkdir -p "$1"; cd "$1"; shift; exec >"$1"; shift; "$@"',
        'sh',                       # argv[0]
        '/src/files',               # working directory
        '/src/files/Sources',
        'dpkg-scansources',
        '.',
    ])

    with open(
        os.path.join(parent, 'Sources.gz'), 'wb'
    ) as binary_writer:
        subprocess.check_call([
            'pigz', '-c', '-n', '--rsyncable',
            os.path.join(parent, 'Sources'),
        ], stdout=binary_writer)

    os.remove(os.path.join(parent, 'Sources'))

    try:
        with open(
            os.path.join(parent, 'sources.txt'), 'r'
        ) as reader:
            for line in reader:
                if line.startswith('#'):
                    continue

                source, source_version = line.rstrip('\n').split('\t')[:2]
                included.add(SourceRequired(source, source_version))
    except OSError:
        pass

    with open(
        os.path.join(parent, 'sources.txt'), 'w'
    ) as writer:
        writer.write('#Source\t#Version\n')

        for s in sorted(included):
            writer.write('{}\t{}\n'.format(s.source, s.source_version))

    if missing_sources:
        logger.warning('Missing source packages:')

        try:
            with open(
                os.path.join(parent, 'MISSING.txt'), 'r'
            ) as reader:
                for line in reader:
                    if line.startswith('#'):
                        continue

                    source, source_version = line.rstrip('\n').split('\t')[:2]
                    missing_sources.add(SourceRequired(source, source_version))
        except OSError:
            pass

        with open(
            os.path.join(parent, 'MISSING.txt'), 'w'
        ) as writer:
            writer.write('#Source\t#Version\n')

            for s in sorted(missing_sources):
                logger.warning('- %s', s)
                writer.write('{}\t{}\n'.format(s.source, s.source_version))

        logger.warning('Check that this runtime is GPL-compliant!')


if __name__ == '__main__':
    if sys.stderr.isatty():
        try:
            import colorlog
        except ImportError:
            logging.basicConfig()
        else:
            formatter = colorlog.ColoredFormatter(
                '%(log_color)s%(levelname)s:%(name)s:%(reset)s %(message)s')
            handler = logging.StreamHandler()
            handler.setFormatter(formatter)
            logging.getLogger().addHandler(handler)
    else:
        logging.basicConfig()

    logging.getLogger().setLevel(logging.DEBUG)

    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit(130)
    except subprocess.CalledProcessError as e:
        logger.error('%s', e)
        raise SystemExit(1)
