# Copyright 2019-2022 Collabora Ltd.
# SPDX-License-Identifier: MIT

FROM scratch
ADD @sysroot_tarball@ /
RUN \
set -e; \
if [ "@nopasswd@" = true ]; then \
    mkdir -p /etc/sudoers.d; \
    echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/flatdeb; \
    chmod 0440 /etc/sudoers.d/flatdeb; \
fi; \
:

@os_release_labels@
@comment_if_not_toolbx@LABEL com.github.containers.toolbox="true"
@comment_if_not_toolbx@LABEL com.github.debarshiray.toolbox="true"

CMD ["/bin/bash"]

# vim:set sw=4 sts=4 et:
