# Copyright 2019 Collabora Ltd.
# SPDX-License-Identifier: MIT

FROM scratch
ADD @sysroot_tarball@ /
RUN \
set -e; \
mkdir -p /run/systemd; \
echo 'docker' > /run/systemd/container; \
:

CMD ["/bin/bash"]

# vim:set sw=4 sts=4 et:
