#!/bin/bash

# Copyright © 2016-2017 Simon McVittie
# Copyright © 2017-2018 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e
set -u
set -x
set -o pipefail

me="$(basename "$0")"
NULL=

if [ "$#" != 0 ] || [ "x$(id -u)" != x0 ]; then
    echo "$me: Usage:" >&2
    echo "    $me" >&2
    echo "" >&2
    echo "Run this script as root, in the container." >&2
    exit 2
fi

find / -xdev '(' \
    -lname '/etc/alternatives/*' -o \
    -lname '/etc/locale.alias' \
')' -exec sh -euc '
while [ $# -gt 0 ]; do
    old="$(readlink "$1")"
    if target="$(readlink -f "$1")"; then
        echo "Making $1 a hard link to $target (was $old)"
        rm -f "$1"
        cp -al "$target" "$1"
    fi
    shift
done
' \
'sh' \
'{}' '+'
# In the above, 'sh' before '{}' is argv[0]

# vim:set sw=4 sts=4 et:
