#!/bin/bash

# Copyright © 2016-2017 Simon McVittie
# Copyright © 2017-2018 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e
set -u
set -x
set -o pipefail

me="$(basename "$0")"
NULL=

if [ "$#" != 1 ] || [ "$1" = '--help' ] || [ "x$(id -u)" != x0 ] ||
        ! [ -d "$1" ]; then
    echo "$me: Usage:" >&2
    echo "    $me SYSROOT" >&2
    echo "" >&2
    echo "Run this script as root." >&2
    exit 2
fi

sysroot="$1"
cd "$sysroot"

in_chroot () {
    local var

    for var in ftp_proxy http_proxy https_proxy no_proxy; do
        if [ -n "${!var-}" ]; then
            set -- "${var}=${!var}" "$@"
        fi
    done

    systemd-nspawn --directory="$sysroot" --as-pid2 \
    env DEBIAN_FRONTEND=noninteractive \
    "$@"
}

DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND

install -d \
"$sysroot/run/lock" \
"$sysroot/var/cache/apt/archives/partial" \
"$sysroot/var/lib/apt/lists" \
"$sysroot/var/lock" \
${NULL}

# We use aptitude to help prepare the Platform runtime, and
# it's a useful thing to have in the Sdk runtime
in_chroot apt-get -q -y --no-install-recommends install aptitude

# All packages will be removed from the platform runtime
# unless they are Essential, depended-on, or in the
# add_packages list.
in_chroot aptitude -y markauto '?installed'

# Ubuntu precise doesn't like apt being up for autoremoval.
in_chroot aptitude -y unmarkauto apt

# Required for openjdk-8-jre-headless
install -d "$sysroot/usr/share/man/man1"
