#!/bin/bash

# Copyright © 2016-2017 Simon McVittie
# Copyright © 2017-2019 Collabora Ltd.
#
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e
set -u
set -o pipefail

me="$(basename "$0")"

if [ "$#" != 1 ] || [ "$1" = '--help' ] || [ "x$(id -u)" != x0 ] ||
        ! [ -d "$1" ]; then
    echo "$me: Usage:" >&2
    echo "    $me SYSROOT" >&2
    echo "" >&2
    echo "Run this script as root." >&2
    exit 2
fi

sysroot="$1"
cd "$sysroot"

in_chroot () {
    chroot "$sysroot" "$@"
}

in_chroot find / -xdev '(' \
    -lname '/etc/alternatives/*' -o \
    -lname '/etc/locale.alias' \
')' -exec sh -euc '
while [ $# -gt 0 ]; do
    old="$(readlink "$1")"
    if target="$(readlink -f "$1")"; then
        rel_target="$target"    # /usr/bin/more
        rel_link="$1"           # /usr/bin/pager
        target_top="${rel_target#/}"    # usr/bin/more
        target_top="${target_top%%/*}"  # usr
        link_top="${rel_link#/}"        # usr/bin/pager
        link_top="${link_top%%/*}"    # usr
        if [ "$target_top" = "$link_top" ]; then
            # While the part up to the first / is equal, remove it
            while [ "${rel_target%%/*}" = "${rel_link%%/*}" ]; do
                rel_target="${rel_target#*/}"
                rel_link="${rel_link#*/}"
            done
            # If the link has directories, add enough ../ to escape
            while [ "${rel_link#*/}" != "${rel_link}" ]; do
                rel_link="${rel_link#*/}"
                rel_target="../${rel_target}"
            done
        fi
        echo "Making $1 a symlink to $rel_target (was $old -> ... -> $target)"
        ln -fns "$rel_target" "$1"
    fi
    shift
done
' \
'sh' \
'{}' '+'
# In the above, 'sh' before '{}' is argv[0]

# vim:set sw=4 sts=4 et:
