name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build runtime
    runs-on: ubuntu-latest
    steps:
    - name: Prepare host
      run: sudo apt update && sudo apt install binutils debootstrap debos dpkg-dev flatpak flatpak-builder ostree pigz python3 python3-debian python3-gi python3-yaml systemd-container time

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive

    - name: Make base
      run: subprojects/flatdeb/run.py --suite=sniper --arch=amd64,i386 base

    - name: Make runtime
      run: subprojects/flatdeb/run.py --suite=sniper --arch=amd64,i386 --no-collect-source-code --no-debug-symbols --no-generate-source-tarball --ostree-commit --platform runtimes runtimes/sniper.yaml

    - name: Compress flatdeb
      run: tar -cfv - ~/.cache/flatdeb/repo | zstd -T0 --ultra -22 > flatdeb.tar.zst

    - name: Upload to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flatdeb.tar.gz
        path: flatdeb.tar.zst